### ISSUE TITLE
"undefined method `&'" error

### ISSUE THREAD

**Issue by kjnilsson** [wkf/fluent-plugin-riemann#3]
I get the following error when trying to use the fluentd riemann plugin. 

2015-07-14 11:49:29 +0100 [warn]: temporarily failed to flush the buffer. next_retry=2015-07-14 11:49:30 +0100 error_class="NoMethodError" error="undefined method `&' for 1436870957.640452:Float" plugin_id="object:f581b0"
  2015-07-14 11:49:29 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/beefcake-1.1.0/lib/beefcake/buffer/encode.rb:86:in`append_uint64'
  2015-07-14 11:49:29 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/beefcake-1.1.0/lib/beefcake/buffer/encode.rb:61:in `append_int64'
  2015-07-14 11:49:29 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/beefcake-1.1.0/lib/beefcake/buffer/encode.rb:13:in`append'
  2015-07-14 11:49:29 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/beefcake-1.1.0/lib/beefcake.rb:126:in `block in encode!'
  2015-07-14 11:49:29 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/beefcake-1.1.0/lib/beefcake.rb:114:in`each'
  2015-07-14 11:49:29 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/beefcake-1.1.0/lib/beefcake.rb:114:in `encode!'
  2015-07-14 11:49:29 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/beefcake-1.1.0/lib/beefcake.rb:103:in`block in encode'
  2015-07-14 11:49:29 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/beefcake-1.1.0/lib/beefcake.rb:96:in `each'
  2015-07-14 11:49:29 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/beefcake-1.1.0/lib/beefcake.rb:96:in`encode'
  2015-07-14 11:49:29 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/beefcake-1.1.0/lib/beefcake.rb:118:in `block in encode!'
  2015-07-14 11:49:29 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/beefcake-1.1.0/lib/beefcake.rb:114:in`each'
  2015-07-14 11:49:29 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/beefcake-1.1.0/lib/beefcake.rb:114:in `encode!'
  2015-07-14 11:49:29 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/beefcake-1.1.0/lib/beefcake.rb:103:in`block in encode'
  2015-07-14 11:49:29 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/beefcake-1.1.0/lib/beefcake.rb:96:in `each'
  2015-07-14 11:49:29 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/beefcake-1.1.0/lib/beefcake.rb:96:in`encode'
  2015-07-14 11:49:29 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/riemann-client-0.2.5/lib/riemann/message.rb:12:in `encode_with_length'
  2015-07-14 11:49:29 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/riemann-client-0.2.5/lib/riemann/client/tcp.rb:78:in`block in send_recv'
  2015-07-14 11:49:29 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/riemann-client-0.2.5/lib/riemann/client/tcp.rb:92:in `block in with_connection'
  2015-07-14 11:49:29 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/monitor.rb:211:in`mon_synchronize'
  2015-07-14 11:49:29 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/riemann-client-0.2.5/lib/riemann/client/tcp.rb:89:in `with_connection'
  2015-07-14 11:49:29 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/riemann-client-0.2.5/lib/riemann/client/tcp.rb:77:in`send_recv'
  2015-07-14 11:49:29 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/riemann-client-0.2.5/lib/riemann/client.rb:63:in `<<'
  2015-07-14 11:49:29 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-riemann-0.0.3/lib/fluent/plugin/out_riemann.rb:61:in`block in write'
  2015-07-14 11:49:29 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/plugin/buf_memory.rb:61:in `feed_each'
  2015-07-14 11:49:29 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/plugin/buf_memory.rb:61:in`msgpack_each'
  2015-07-14 11:49:29 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-riemann-0.0.3/lib/fluent/plugin/out_riemann.rb:51:in `write'
  2015-07-14 11:49:29 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/buffer.rb:325:in`write_chunk'
  2015-07-14 11:49:29 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/buffer.rb:304:in `pop'
  2015-07-14 11:49:29 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/output.rb:321:in`try_flush'

config:
 <store>
    type riemann
    host btn-docker-03
    #port 5555
    timeout 60
    protocol tcp
    service logs
    fields message:description,level:state
    types metric:float
    flush_interval 10s
  </store>

td-agent version: 0.12.12

**Comment by kjnilsson** [comment]
Server version: Ubuntu 12.04.5 LTS
